# Generated by Django 4.0 on 2021-12-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0002_alter_employee_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
